### PR TITLE
do not reload answers if fail to generate

### PR DESCRIPTION
**Pull request by alena1108**

### CODE REVIEW

**Comment by mattdodge** [comment]
I believe this at least partially fixes https://github.com/rancher/rancher/issues/9894. Doesn't address the reason the timeouts are happening but at least prevents it from wiping out all of the old answers

**Comment by ptempier** [comment]
@deniseschannon 
Please put this in stable 2.x and backport to 1.x.
It does a very heavy mitigation of the metadata behavior (being asynchrone) and is very legitimate behavior (ignoring bad input data).

**Comment by superseb** [comment]
@ptempier This will be in v1.6.15 (if tests are OK)

**Comment by peregrinator** [comment]
We're experiencing this in production as well, what's the timeline for 1.6.15? Thanks!

**Comment by superseb** [comment]
Mid/End of March

**Pull request merged**
