### PR TITLE
Fixes non-standard handling of queries

### PR DESCRIPTION
**Pull request by janeczku**
Fixes query handling that did not conform with DNS standards and therefore broke DNS resolution for Alpine Linux 3.4+ based images on Cattle and K8s.
https://github.com/rancher/rancher/issues/5041
https://github.com/rancher/rancher/issues/7026

### CODE REVIEW

**Comment by vincent99** [comment]
@janeczku This has been very sensitive to changes in the past against quirks in various clients so I'm pretty hesitant to merge anything significant here... would you be interested in writing a test suite for it?  The manual cases I've done stuff with in the past are in example/answers.json.

For example this appears to now be reliant on the client's search path and no longer work if you ask for something unqualified, i.e.

```
./rancher-dns -listen ":5333" -answers ./example/answers.json  -debug &
dig -p 5333 @localhost c  # not found
dig -p 5333 @localhost c +domain=rancher.internal  # not found
dig -p 5333 @localhost c.x +domain=rancher.internal  # found
dig -p 5333 @localhost c +domain=x.rancher.internal  # found

```

...but the server-side search path resolution was AFAIR a hack for alpine, which has since changed and has less of a crappy resolver in the first place so it's possible we don't even still need it.

**Comment by vincent99** [comment]
SEARCH_MAX_LABELS can default have a default but should come from an option in the answers file.. the actual code knows nothing about Rancher specifically or the answer files it generates happening to need 3.

**Comment by janeczku** [comment]
@vincent99 Yeah i was wondering about the reason for that search hack :pick: . Support for search in resolv.conf was introduced in Alpine Linux v3.4. Obviously many images out there (including ours) are still based off of earlier Alpine base images and won't do any of that search stuff.
I'll look into adding integration tests for the typical queries. Definitely makes sense to do that.

**Comment by janeczku** [comment]
@vincent99 rebased and removed the `SEARCH_MAX_LABELS` logic for now.

**Comment by janeczku** [comment]
@vincent99 your test probably failed because you were using `localhost` in your dig command which on MacOS resolves to IPv6 (http://superuser.com/questions/914443/os-x-localhost-resolving-strangely).

To be clear, this PR does **not** remove the search hack we did for previous Alpine versions.

```
$ ./rancher-dns -listen ":5333" -answers ./example/answers.json  -debug &
$ dig -p 5333 @127.0.0.1 c
; <<>> DiG 9.8.3-P1 <<>> -p 5333 @127.0.0.1 c
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43265
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;c.				IN	A

;; ANSWER SECTION:
c.			600	IN	A	1.2.3.6
```

**Comment by alena1108** [comment]
With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches

**Pull request closed without merging**
